// @generated by protobuf-ts 2.9.1 with parameter long_type_string,generate_dependencies,optimize_code_size
// @generated from protobuf file "impl/v1/impl.proto" (package "impl.v1", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { CheckedExpr } from "../../google/api/expr/v1alpha1/checked";
/**
 * @generated from protobuf message impl.v1.DecodedCaveat
 */
export interface DecodedCaveat {
    /**
     * @generated from protobuf oneof: kind_oneof
     */
    kindOneof: {
        oneofKind: "cel";
        /**
         * @generated from protobuf field: google.api.expr.v1alpha1.CheckedExpr cel = 1;
         */
        cel: CheckedExpr;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
}
/**
 * @generated from protobuf message impl.v1.DecodedZookie
 */
export interface DecodedZookie {
    /**
     * @generated from protobuf field: uint32 version = 1;
     */
    version: number;
    /**
     * @generated from protobuf oneof: version_oneof
     */
    versionOneof: {
        oneofKind: "v1";
        /**
         * @generated from protobuf field: impl.v1.DecodedZookie.V1Zookie v1 = 2;
         */
        v1: DecodedZookie_V1Zookie;
    } | {
        oneofKind: "v2";
        /**
         * @generated from protobuf field: impl.v1.DecodedZookie.V2Zookie v2 = 3;
         */
        v2: DecodedZookie_V2Zookie;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message impl.v1.DecodedZookie.V1Zookie
 */
export interface DecodedZookie_V1Zookie {
    /**
     * @generated from protobuf field: uint64 revision = 1;
     */
    revision: string;
}
/**
 * @generated from protobuf message impl.v1.DecodedZookie.V2Zookie
 */
export interface DecodedZookie_V2Zookie {
    /**
     * @generated from protobuf field: string revision = 1;
     */
    revision: string;
}
/**
 * @generated from protobuf message impl.v1.DecodedZedToken
 */
export interface DecodedZedToken {
    /**
     * @generated from protobuf oneof: version_oneof
     */
    versionOneof: {
        oneofKind: "deprecatedV1Zookie";
        /**
         * @generated from protobuf field: impl.v1.DecodedZedToken.V1Zookie deprecated_v1_zookie = 2;
         */
        deprecatedV1Zookie: DecodedZedToken_V1Zookie;
    } | {
        oneofKind: "v1";
        /**
         * @generated from protobuf field: impl.v1.DecodedZedToken.V1ZedToken v1 = 3;
         */
        v1: DecodedZedToken_V1ZedToken;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message impl.v1.DecodedZedToken.V1Zookie
 */
export interface DecodedZedToken_V1Zookie {
    /**
     * @generated from protobuf field: uint64 revision = 1;
     */
    revision: string;
}
/**
 * @generated from protobuf message impl.v1.DecodedZedToken.V1ZedToken
 */
export interface DecodedZedToken_V1ZedToken {
    /**
     * @generated from protobuf field: string revision = 1;
     */
    revision: string;
}
/**
 * @generated from protobuf message impl.v1.DecodedCursor
 */
export interface DecodedCursor {
    /**
     * @generated from protobuf oneof: version_oneof
     */
    versionOneof: {
        oneofKind: "v1";
        /**
         * @generated from protobuf field: impl.v1.V1Cursor v1 = 1;
         */
        v1: V1Cursor;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message impl.v1.V1Cursor
 */
export interface V1Cursor {
    /**
     * revision is the string form of the revision for the cursor.
     *
     * @generated from protobuf field: string revision = 1;
     */
    revision: string;
    /**
     * sections are the sections of the dispatching cursor.
     *
     * @generated from protobuf field: repeated string sections = 2;
     */
    sections: string[];
    /**
     * call_and_parameters_hash is a hash of the call that manufactured this cursor and all its
     * parameters, including limits and zedtoken, to ensure no inputs changed when using this cursor.
     *
     * @generated from protobuf field: string call_and_parameters_hash = 3;
     */
    callAndParametersHash: string;
    /**
     * dispatch_version is the version of the dispatcher which created the cursor.
     *
     * @generated from protobuf field: uint32 dispatch_version = 4;
     */
    dispatchVersion: number;
    /**
     * flags are flags set by the API caller.
     *
     * @generated from protobuf field: map<string, string> flags = 5;
     */
    flags: {
        [key: string]: string;
    };
}
/**
 * @generated from protobuf message impl.v1.DocComment
 */
export interface DocComment {
    /**
     * @generated from protobuf field: string comment = 1;
     */
    comment: string;
}
/**
 * @generated from protobuf message impl.v1.RelationMetadata
 */
export interface RelationMetadata {
    /**
     * @generated from protobuf field: impl.v1.RelationMetadata.RelationKind kind = 1;
     */
    kind: RelationMetadata_RelationKind;
}
/**
 * @generated from protobuf enum impl.v1.RelationMetadata.RelationKind
 */
export enum RelationMetadata_RelationKind {
    /**
     * @generated from protobuf enum value: UNKNOWN_KIND = 0;
     */
    UNKNOWN_KIND = 0,
    /**
     * @generated from protobuf enum value: RELATION = 1;
     */
    RELATION = 1,
    /**
     * @generated from protobuf enum value: PERMISSION = 2;
     */
    PERMISSION = 2
}
/**
 * @generated from protobuf message impl.v1.NamespaceAndRevision
 */
export interface NamespaceAndRevision {
    /**
     * @generated from protobuf field: string namespace_name = 1;
     */
    namespaceName: string;
    /**
     * @generated from protobuf field: string revision = 2;
     */
    revision: string;
}
/**
 * @generated from protobuf message impl.v1.V1Alpha1Revision
 */
export interface V1Alpha1Revision {
    /**
     * @generated from protobuf field: repeated impl.v1.NamespaceAndRevision ns_revisions = 1;
     */
    nsRevisions: NamespaceAndRevision[];
}
// @generated message type with reflection information, may provide speed optimized methods
class DecodedCaveat$Type extends MessageType<DecodedCaveat> {
    constructor() {
        super("impl.v1.DecodedCaveat", [
            { no: 1, name: "cel", kind: "message", oneof: "kindOneof", T: () => CheckedExpr },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message impl.v1.DecodedCaveat
 */
export const DecodedCaveat = new DecodedCaveat$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DecodedZookie$Type extends MessageType<DecodedZookie> {
    constructor() {
        super("impl.v1.DecodedZookie", [
            { no: 1, name: "version", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "v1", kind: "message", oneof: "versionOneof", T: () => DecodedZookie_V1Zookie },
            { no: 3, name: "v2", kind: "message", oneof: "versionOneof", T: () => DecodedZookie_V2Zookie }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message impl.v1.DecodedZookie
 */
export const DecodedZookie = new DecodedZookie$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DecodedZookie_V1Zookie$Type extends MessageType<DecodedZookie_V1Zookie> {
    constructor() {
        super("impl.v1.DecodedZookie.V1Zookie", [
            { no: 1, name: "revision", kind: "scalar", T: 4 /*ScalarType.UINT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message impl.v1.DecodedZookie.V1Zookie
 */
export const DecodedZookie_V1Zookie = new DecodedZookie_V1Zookie$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DecodedZookie_V2Zookie$Type extends MessageType<DecodedZookie_V2Zookie> {
    constructor() {
        super("impl.v1.DecodedZookie.V2Zookie", [
            { no: 1, name: "revision", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message impl.v1.DecodedZookie.V2Zookie
 */
export const DecodedZookie_V2Zookie = new DecodedZookie_V2Zookie$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DecodedZedToken$Type extends MessageType<DecodedZedToken> {
    constructor() {
        super("impl.v1.DecodedZedToken", [
            { no: 2, name: "deprecated_v1_zookie", kind: "message", oneof: "versionOneof", T: () => DecodedZedToken_V1Zookie },
            { no: 3, name: "v1", kind: "message", oneof: "versionOneof", T: () => DecodedZedToken_V1ZedToken }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message impl.v1.DecodedZedToken
 */
export const DecodedZedToken = new DecodedZedToken$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DecodedZedToken_V1Zookie$Type extends MessageType<DecodedZedToken_V1Zookie> {
    constructor() {
        super("impl.v1.DecodedZedToken.V1Zookie", [
            { no: 1, name: "revision", kind: "scalar", T: 4 /*ScalarType.UINT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message impl.v1.DecodedZedToken.V1Zookie
 */
export const DecodedZedToken_V1Zookie = new DecodedZedToken_V1Zookie$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DecodedZedToken_V1ZedToken$Type extends MessageType<DecodedZedToken_V1ZedToken> {
    constructor() {
        super("impl.v1.DecodedZedToken.V1ZedToken", [
            { no: 1, name: "revision", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message impl.v1.DecodedZedToken.V1ZedToken
 */
export const DecodedZedToken_V1ZedToken = new DecodedZedToken_V1ZedToken$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DecodedCursor$Type extends MessageType<DecodedCursor> {
    constructor() {
        super("impl.v1.DecodedCursor", [
            { no: 1, name: "v1", kind: "message", oneof: "versionOneof", T: () => V1Cursor }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message impl.v1.DecodedCursor
 */
export const DecodedCursor = new DecodedCursor$Type();
// @generated message type with reflection information, may provide speed optimized methods
class V1Cursor$Type extends MessageType<V1Cursor> {
    constructor() {
        super("impl.v1.V1Cursor", [
            { no: 1, name: "revision", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "sections", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "call_and_parameters_hash", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "dispatch_version", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "flags", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message impl.v1.V1Cursor
 */
export const V1Cursor = new V1Cursor$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DocComment$Type extends MessageType<DocComment> {
    constructor() {
        super("impl.v1.DocComment", [
            { no: 1, name: "comment", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message impl.v1.DocComment
 */
export const DocComment = new DocComment$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RelationMetadata$Type extends MessageType<RelationMetadata> {
    constructor() {
        super("impl.v1.RelationMetadata", [
            { no: 1, name: "kind", kind: "enum", T: () => ["impl.v1.RelationMetadata.RelationKind", RelationMetadata_RelationKind] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message impl.v1.RelationMetadata
 */
export const RelationMetadata = new RelationMetadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NamespaceAndRevision$Type extends MessageType<NamespaceAndRevision> {
    constructor() {
        super("impl.v1.NamespaceAndRevision", [
            { no: 1, name: "namespace_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "revision", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message impl.v1.NamespaceAndRevision
 */
export const NamespaceAndRevision = new NamespaceAndRevision$Type();
// @generated message type with reflection information, may provide speed optimized methods
class V1Alpha1Revision$Type extends MessageType<V1Alpha1Revision> {
    constructor() {
        super("impl.v1.V1Alpha1Revision", [
            { no: 1, name: "ns_revisions", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => NamespaceAndRevision }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message impl.v1.V1Alpha1Revision
 */
export const V1Alpha1Revision = new V1Alpha1Revision$Type();
