// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file impl/v1/impl.proto (package impl.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { CheckedExpr } from "../../google/api/expr/v1alpha1/checked_pb";
import { file_google_api_expr_v1alpha1_checked } from "../../google/api/expr/v1alpha1/checked_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file impl/v1/impl.proto.
 */
export const file_impl_v1_impl: GenFile = /*@__PURE__*/
  fileDesc("ChJpbXBsL3YxL2ltcGwucHJvdG8SB2ltcGwudjEiYQoNRGVjb2RlZENhdmVhdBI0CgNjZWwYASABKAsyJS5nb29nbGUuYXBpLmV4cHIudjFhbHBoYTEuQ2hlY2tlZEV4cHJIABIMCgRuYW1lGAIgASgJQgwKCmtpbmRfb25lb2YiywEKDURlY29kZWRab29raWUSDwoHdmVyc2lvbhgBIAEoDRItCgJ2MRgCIAEoCzIfLmltcGwudjEuRGVjb2RlZFpvb2tpZS5WMVpvb2tpZUgAEi0KAnYyGAMgASgLMh8uaW1wbC52MS5EZWNvZGVkWm9va2llLlYyWm9va2llSAAaHAoIVjFab29raWUSEAoIcmV2aXNpb24YASABKAQaHAoIVjJab29raWUSEAoIcmV2aXNpb24YASABKAlCDwoNdmVyc2lvbl9vbmVvZiLWAQoPRGVjb2RlZFplZFRva2VuEkEKFGRlcHJlY2F0ZWRfdjFfem9va2llGAIgASgLMiEuaW1wbC52MS5EZWNvZGVkWmVkVG9rZW4uVjFab29raWVIABIxCgJ2MRgDIAEoCzIjLmltcGwudjEuRGVjb2RlZFplZFRva2VuLlYxWmVkVG9rZW5IABocCghWMVpvb2tpZRIQCghyZXZpc2lvbhgBIAEoBBoeCgpWMVplZFRva2VuEhAKCHJldmlzaW9uGAEgASgJQg8KDXZlcnNpb25fb25lb2YiQQoNRGVjb2RlZEN1cnNvchIfCgJ2MRgBIAEoCzIRLmltcGwudjEuVjFDdXJzb3JIAEIPCg12ZXJzaW9uX29uZW9mIsUBCghWMUN1cnNvchIQCghyZXZpc2lvbhgBIAEoCRIQCghzZWN0aW9ucxgCIAMoCRIgChhjYWxsX2FuZF9wYXJhbWV0ZXJzX2hhc2gYAyABKAkSGAoQZGlzcGF0Y2hfdmVyc2lvbhgEIAEoDRIrCgVmbGFncxgFIAMoCzIcLmltcGwudjEuVjFDdXJzb3IuRmxhZ3NFbnRyeRosCgpGbGFnc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiHQoKRG9jQ29tbWVudBIPCgdjb21tZW50GAEgASgJIogBChBSZWxhdGlvbk1ldGFkYXRhEjQKBGtpbmQYASABKA4yJi5pbXBsLnYxLlJlbGF0aW9uTWV0YWRhdGEuUmVsYXRpb25LaW5kIj4KDFJlbGF0aW9uS2luZBIQCgxVTktOT1dOX0tJTkQQABIMCghSRUxBVElPThABEg4KClBFUk1JU1NJT04QAiJAChROYW1lc3BhY2VBbmRSZXZpc2lvbhIWCg5uYW1lc3BhY2VfbmFtZRgBIAEoCRIQCghyZXZpc2lvbhgCIAEoCSJHChBWMUFscGhhMVJldmlzaW9uEjMKDG5zX3JldmlzaW9ucxgBIAMoCzIdLmltcGwudjEuTmFtZXNwYWNlQW5kUmV2aXNpb25CLlosZ2l0aHViLmNvbS9hdXRoemVkL3NwaWNlZGIvcGtnL3Byb3RvL2ltcGwvdjFiBnByb3RvMw", [file_google_api_expr_v1alpha1_checked]);

/**
 * @generated from message impl.v1.DecodedCaveat
 */
export type DecodedCaveat = Message<"impl.v1.DecodedCaveat"> & {
  /**
   * we do kind_oneof in case we decide to have non-CEL expressions
   *
   * @generated from oneof impl.v1.DecodedCaveat.kind_oneof
   */
  kindOneof: {
    /**
     * @generated from field: google.api.expr.v1alpha1.CheckedExpr cel = 1;
     */
    value: CheckedExpr;
    case: "cel";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message impl.v1.DecodedCaveat.
 * Use `create(DecodedCaveatSchema)` to create a new message.
 */
export const DecodedCaveatSchema: GenMessage<DecodedCaveat> = /*@__PURE__*/
  messageDesc(file_impl_v1_impl, 0);

/**
 * @generated from message impl.v1.DecodedZookie
 */
export type DecodedZookie = Message<"impl.v1.DecodedZookie"> & {
  /**
   * @generated from field: uint32 version = 1;
   */
  version: number;

  /**
   * @generated from oneof impl.v1.DecodedZookie.version_oneof
   */
  versionOneof: {
    /**
     * @generated from field: impl.v1.DecodedZookie.V1Zookie v1 = 2;
     */
    value: DecodedZookie_V1Zookie;
    case: "v1";
  } | {
    /**
     * @generated from field: impl.v1.DecodedZookie.V2Zookie v2 = 3;
     */
    value: DecodedZookie_V2Zookie;
    case: "v2";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message impl.v1.DecodedZookie.
 * Use `create(DecodedZookieSchema)` to create a new message.
 */
export const DecodedZookieSchema: GenMessage<DecodedZookie> = /*@__PURE__*/
  messageDesc(file_impl_v1_impl, 1);

/**
 * @generated from message impl.v1.DecodedZookie.V1Zookie
 */
export type DecodedZookie_V1Zookie = Message<"impl.v1.DecodedZookie.V1Zookie"> & {
  /**
   * @generated from field: uint64 revision = 1;
   */
  revision: bigint;
};

/**
 * Describes the message impl.v1.DecodedZookie.V1Zookie.
 * Use `create(DecodedZookie_V1ZookieSchema)` to create a new message.
 */
export const DecodedZookie_V1ZookieSchema: GenMessage<DecodedZookie_V1Zookie> = /*@__PURE__*/
  messageDesc(file_impl_v1_impl, 1, 0);

/**
 * @generated from message impl.v1.DecodedZookie.V2Zookie
 */
export type DecodedZookie_V2Zookie = Message<"impl.v1.DecodedZookie.V2Zookie"> & {
  /**
   * @generated from field: string revision = 1;
   */
  revision: string;
};

/**
 * Describes the message impl.v1.DecodedZookie.V2Zookie.
 * Use `create(DecodedZookie_V2ZookieSchema)` to create a new message.
 */
export const DecodedZookie_V2ZookieSchema: GenMessage<DecodedZookie_V2Zookie> = /*@__PURE__*/
  messageDesc(file_impl_v1_impl, 1, 1);

/**
 * @generated from message impl.v1.DecodedZedToken
 */
export type DecodedZedToken = Message<"impl.v1.DecodedZedToken"> & {
  /**
   * @generated from oneof impl.v1.DecodedZedToken.version_oneof
   */
  versionOneof: {
    /**
     * @generated from field: impl.v1.DecodedZedToken.V1Zookie deprecated_v1_zookie = 2;
     */
    value: DecodedZedToken_V1Zookie;
    case: "deprecatedV1Zookie";
  } | {
    /**
     * @generated from field: impl.v1.DecodedZedToken.V1ZedToken v1 = 3;
     */
    value: DecodedZedToken_V1ZedToken;
    case: "v1";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message impl.v1.DecodedZedToken.
 * Use `create(DecodedZedTokenSchema)` to create a new message.
 */
export const DecodedZedTokenSchema: GenMessage<DecodedZedToken> = /*@__PURE__*/
  messageDesc(file_impl_v1_impl, 2);

/**
 * @generated from message impl.v1.DecodedZedToken.V1Zookie
 */
export type DecodedZedToken_V1Zookie = Message<"impl.v1.DecodedZedToken.V1Zookie"> & {
  /**
   * @generated from field: uint64 revision = 1;
   */
  revision: bigint;
};

/**
 * Describes the message impl.v1.DecodedZedToken.V1Zookie.
 * Use `create(DecodedZedToken_V1ZookieSchema)` to create a new message.
 */
export const DecodedZedToken_V1ZookieSchema: GenMessage<DecodedZedToken_V1Zookie> = /*@__PURE__*/
  messageDesc(file_impl_v1_impl, 2, 0);

/**
 * @generated from message impl.v1.DecodedZedToken.V1ZedToken
 */
export type DecodedZedToken_V1ZedToken = Message<"impl.v1.DecodedZedToken.V1ZedToken"> & {
  /**
   * @generated from field: string revision = 1;
   */
  revision: string;
};

/**
 * Describes the message impl.v1.DecodedZedToken.V1ZedToken.
 * Use `create(DecodedZedToken_V1ZedTokenSchema)` to create a new message.
 */
export const DecodedZedToken_V1ZedTokenSchema: GenMessage<DecodedZedToken_V1ZedToken> = /*@__PURE__*/
  messageDesc(file_impl_v1_impl, 2, 1);

/**
 * @generated from message impl.v1.DecodedCursor
 */
export type DecodedCursor = Message<"impl.v1.DecodedCursor"> & {
  /**
   * we do version_oneof in case we decide to add a new version.
   *
   * @generated from oneof impl.v1.DecodedCursor.version_oneof
   */
  versionOneof: {
    /**
     * @generated from field: impl.v1.V1Cursor v1 = 1;
     */
    value: V1Cursor;
    case: "v1";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message impl.v1.DecodedCursor.
 * Use `create(DecodedCursorSchema)` to create a new message.
 */
export const DecodedCursorSchema: GenMessage<DecodedCursor> = /*@__PURE__*/
  messageDesc(file_impl_v1_impl, 3);

/**
 * @generated from message impl.v1.V1Cursor
 */
export type V1Cursor = Message<"impl.v1.V1Cursor"> & {
  /**
   * revision is the string form of the revision for the cursor.
   *
   * @generated from field: string revision = 1;
   */
  revision: string;

  /**
   * sections are the sections of the dispatching cursor.
   *
   * @generated from field: repeated string sections = 2;
   */
  sections: string[];

  /**
   * call_and_parameters_hash is a hash of the call that manufactured this cursor and all its
   * parameters, including limits and zedtoken, to ensure no inputs changed when using this cursor.
   *
   * @generated from field: string call_and_parameters_hash = 3;
   */
  callAndParametersHash: string;

  /**
   * dispatch_version is the version of the dispatcher which created the cursor.
   *
   * @generated from field: uint32 dispatch_version = 4;
   */
  dispatchVersion: number;

  /**
   * flags are flags set by the API caller.
   *
   * @generated from field: map<string, string> flags = 5;
   */
  flags: { [key: string]: string };
};

/**
 * Describes the message impl.v1.V1Cursor.
 * Use `create(V1CursorSchema)` to create a new message.
 */
export const V1CursorSchema: GenMessage<V1Cursor> = /*@__PURE__*/
  messageDesc(file_impl_v1_impl, 4);

/**
 * @generated from message impl.v1.DocComment
 */
export type DocComment = Message<"impl.v1.DocComment"> & {
  /**
   * @generated from field: string comment = 1;
   */
  comment: string;
};

/**
 * Describes the message impl.v1.DocComment.
 * Use `create(DocCommentSchema)` to create a new message.
 */
export const DocCommentSchema: GenMessage<DocComment> = /*@__PURE__*/
  messageDesc(file_impl_v1_impl, 5);

/**
 * @generated from message impl.v1.RelationMetadata
 */
export type RelationMetadata = Message<"impl.v1.RelationMetadata"> & {
  /**
   * @generated from field: impl.v1.RelationMetadata.RelationKind kind = 1;
   */
  kind: RelationMetadata_RelationKind;
};

/**
 * Describes the message impl.v1.RelationMetadata.
 * Use `create(RelationMetadataSchema)` to create a new message.
 */
export const RelationMetadataSchema: GenMessage<RelationMetadata> = /*@__PURE__*/
  messageDesc(file_impl_v1_impl, 6);

/**
 * @generated from enum impl.v1.RelationMetadata.RelationKind
 */
export enum RelationMetadata_RelationKind {
  /**
   * @generated from enum value: UNKNOWN_KIND = 0;
   */
  UNKNOWN_KIND = 0,

  /**
   * @generated from enum value: RELATION = 1;
   */
  RELATION = 1,

  /**
   * @generated from enum value: PERMISSION = 2;
   */
  PERMISSION = 2,
}

/**
 * Describes the enum impl.v1.RelationMetadata.RelationKind.
 */
export const RelationMetadata_RelationKindSchema: GenEnum<RelationMetadata_RelationKind> = /*@__PURE__*/
  enumDesc(file_impl_v1_impl, 6, 0);

/**
 * @generated from message impl.v1.NamespaceAndRevision
 */
export type NamespaceAndRevision = Message<"impl.v1.NamespaceAndRevision"> & {
  /**
   * @generated from field: string namespace_name = 1;
   */
  namespaceName: string;

  /**
   * @generated from field: string revision = 2;
   */
  revision: string;
};

/**
 * Describes the message impl.v1.NamespaceAndRevision.
 * Use `create(NamespaceAndRevisionSchema)` to create a new message.
 */
export const NamespaceAndRevisionSchema: GenMessage<NamespaceAndRevision> = /*@__PURE__*/
  messageDesc(file_impl_v1_impl, 7);

/**
 * @generated from message impl.v1.V1Alpha1Revision
 */
export type V1Alpha1Revision = Message<"impl.v1.V1Alpha1Revision"> & {
  /**
   * @generated from field: repeated impl.v1.NamespaceAndRevision ns_revisions = 1;
   */
  nsRevisions: NamespaceAndRevision[];
};

/**
 * Describes the message impl.v1.V1Alpha1Revision.
 * Use `create(V1Alpha1RevisionSchema)` to create a new message.
 */
export const V1Alpha1RevisionSchema: GenMessage<V1Alpha1Revision> = /*@__PURE__*/
  messageDesc(file_impl_v1_impl, 8);

