---
name: "Run Tests"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  test:
    name: "Run Tests"
    runs-on: "depot-ubuntu-24.04-4"
    steps:
      - uses: "actions/checkout@v6"
        with:
          lfs: true
          submodules: true
      - uses: "pnpm/action-setup@v6"
        with:
          cache: true
      - name: "Install dependencies"
        run: "pnpm install"
      - name: "Install chromium for playwright"
        run: "pnpm test:install-chromium-headless"
      - name: "Run tests"
        run: "pnpm test"
      - name: "Upload test artifacts"
        if: "failure()"
        uses: "actions/upload-artifact@v4"
        with:
          name: "test-screenshots"
          path: "src/tests/browser/__screenshots__"
